"""Generates src/generated/patch_tables.h from scripts/patch_defs.py (the byte patches, per feature).
Run:  python scripts/gen_patch_tables.py
"""
import os
import re
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, os.path.join(ROOT, "scripts"))
import patch_defs as d  # noqa: E402

clamps = [(f"HUD: layout clamp 0x{va}", int(va, 16), o, n, False)
          for va, o, n in re.findall(r"([0-9A-F]{8}) ([0-9A-F]+) ([0-9A-F]+)", d.LAYOUT_CLAMPS)]
groups = {
    "kWidescreen": d.WIDESCREEN,
    "kHud": d.HUD + clamps,
    "kPad": d.CONTROLLER,
    "kTiming": d.TIMING,
}


def arr(h):
    return "{" + ",".join(f"0x{h[i:i + 2]}" for i in range(0, len(h), 2)) + "}"


lines = ["// Generated by scripts/gen_patch_tables.py from scripts/patch_defs.py - do not edit.", "#pragma once",
         '#include "core/patch.h"', "", "namespace gen {"]
for g, entries in groups.items():
    for i, (name, va, o, n, anyv) in enumerate(entries):
        assert len(o) == len(n), name
        lines.append(f"inline constexpr uint8_t {g}_o{i}[] = {arr(o)};")
        lines.append(f"inline constexpr uint8_t {g}_n{i}[] = {arr(n)};")
    lines.append(f"inline constexpr BytePatch {g}[] = {{")
    for i, (name, va, o, n, anyv) in enumerate(entries):
        lines.append(f'    {{DS_PATCH_NAME("{name}"), 0x{va:08X}, {g}_o{i}, {g}_n{i}, {len(o) // 2}, '
                     f'{"true" if anyv else "false"}}},')
    lines.append("};")
lines.append("}  // namespace gen\n")
dst = os.path.join(ROOT, "src", "generated", "patch_tables.h")
os.makedirs(os.path.dirname(dst), exist_ok=True)
open(dst, "w", newline="\n").write("\n".join(lines))
for g, e in groups.items():
    print(f"{g}: {len(e)} patches, {sum(len(x[2]) // 2 for x in e)} bytes")
