"""Bakes the launcher's button-prompt icons into src/generated/prompt_icons.h.
Run:  python scripts/gen_prompt_icons.py        (needs Pillow)

Source: assets/input-prompts (Kenney "Input Prompts" 1.5, CC0 - see License.txt there).
Icons are scaled to SIZE px and stored as premultiplied BGRA for AlphaBlend, so the DLL ships no image files and
decodes nothing at runtime. White-only icons (Options/Menu, keyboard keys) are inverted so they read on light dialogs.
"""
import os
from PIL import Image, ImageOps

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SRC = os.path.join(ROOT, "assets", "input-prompts")
DST = os.path.join(ROOT, "src", "generated", "prompt_icons.h")
SIZE = 20

PS, XB, KB = "PlayStation Series/Default", "Xbox Series/Default", "Keyboard & Mouse/Default"
ICONS = [  # enum name, file, invert
    ("PsCross", f"{PS}/playstation_button_color_cross.png", False),
    ("PsCircle", f"{PS}/playstation_button_color_circle.png", False),
    ("PsTriangle", f"{PS}/playstation_button_color_triangle.png", False),
    ("PsSquare", f"{PS}/playstation_button_color_square.png", False),
    ("PsOptions", f"{PS}/playstation5_button_options.png", True),
    ("PsDpadVertical", f"{PS}/playstation_dpad_vertical.png", False),
    ("PsDpadHorizontal", f"{PS}/playstation_dpad_horizontal.png", False),
    ("XbA", f"{XB}/xbox_button_color_a.png", False),
    ("XbB", f"{XB}/xbox_button_color_b.png", False),
    ("XbX", f"{XB}/xbox_button_color_x.png", False),
    ("XbY", f"{XB}/xbox_button_color_y.png", False),
    ("XbMenu", f"{XB}/xbox_button_menu.png", True),
    ("XbDpadVertical", f"{XB}/xbox_dpad_vertical.png", False),
    ("XbDpadHorizontal", f"{XB}/xbox_dpad_horizontal.png", False),
    ("KbEnter", f"{KB}/keyboard_enter.png", True),
    ("KbEscape", f"{KB}/keyboard_escape.png", True),
]


def load(path, invert):
    im = Image.open(os.path.join(SRC, path)).convert("RGBA")
    if invert:
        r, g, b, a = im.split()
        im = Image.merge("RGBA", (*ImageOps.invert(Image.merge("RGB", (r, g, b))).split(), a))
    return im.resize((SIZE, SIZE), Image.LANCZOS)


def pixels(im):
    out = []
    raw = im.tobytes()  # RGBA
    for i in range(0, len(raw), 4):
        r, g, b, a = raw[i:i + 4]
        r, g, b = (c * a // 255 for c in (r, g, b))  # premultiplied for AlphaBlend
        out.append(f"0x{a:02X}{r:02X}{g:02X}{b:02X}")
    return out


lines = ["// Generated by scripts/gen_prompt_icons.py from assets/input-prompts (Kenney, CC0) - do not edit.",
         "#pragma once", "#include <cstdint>", "", "namespace gen {",
         f"inline constexpr int kPromptIconSize = {SIZE};",
         "enum class PromptIcon { " + ", ".join(n for n, _, _ in ICONS) + ", Count };",
         f"// Premultiplied BGRA (0xAARRGGBB), {SIZE}x{SIZE}, top-down.",
         f"inline constexpr uint32_t kPromptIcons[][{SIZE * SIZE}] = {{"]
for name, path, invert in ICONS:
    px = pixels(load(path, invert))
    lines.append(f"    {{  // {name}")
    for i in range(0, len(px), SIZE):
        lines.append("        " + ",".join(px[i:i + SIZE]) + ",")
    lines.append("    },")
lines += ["};", "}  // namespace gen", ""]
os.makedirs(os.path.dirname(DST), exist_ok=True)
open(DST, "w", newline="\n").write("\n".join(lines))
print(f"{len(ICONS)} icons, {SIZE}px -> {os.path.relpath(DST, ROOT)}")
