"""Controller pictures for the CONTROLLER screen (src/features/controls.cpp).

Source: Zacksly "PS5 Button Icons and Controls" and "Xbox Series Button Icons and Controls" (CC BY 3.0,
https://zacksly.itch.io) - download both zips into the repo root first (third-party archives, not committed).
Modified: cropped to the controller and scaled.
Writes src/generated/controller_ps5.png, controller_xbox.png (RCDATA 301/302 via src/game_icons.rc) and
controller_art.h: image size inside the 2048x1024 texture and, per game button (PS2 numbering 0-15, then 16 left
stick, 17 right stick), where the callout line starts, as fractions of the image.
Run: python scripts/gen_controller_art.py
"""
import io
import os
import zipfile

from PIL import Image

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
GEN = os.path.join(ROOT, "src", "generated")
TEX_W, TEX_H = 2048, 1024

# Button centres in the 4096x2160 source art, game order: Triangle Circle Cross Square L2 R2 L1 R1 Select L3 R3
# Start, D-pad up right down left, left stick, right stick (L3/R3 = the stick itself).
PS5 = [(2667, 671), (2813, 818), (2667, 966), (2520, 818), (1379, 459), (2718, 459), (1428, 500), (2668, 500),
       (1584, 599), (1724, 1092), (2369, 1092), (2512, 599), (1424, 715), (1535, 818), (1424, 925), (1313, 818),
       (1724, 1092), (2369, 1092)]
XBOX = [(2489, 693), (2606, 810), (2489, 924), (2376, 810), (1595, 495), (2502, 495), (1541, 548), (2556, 548),
        (1921, 809), (1601, 815), (2275, 1072), (2173, 809), (1816, 1000), (1905, 1090), (1816, 1180), (1727, 1090),
        (1601, 815), (2275, 1072)]


def build(pack, anchors, out_png):
    z = zipfile.ZipFile(os.path.join(ROOT, f"{pack} Button Icons and Controls.zip"))
    im = Image.open(io.BytesIO(z.read(f"{pack} Button Icons and Controls/Controller Images/Solid/Solid Color 4k.png")))
    im = im.convert("RGBA")
    box = im.getchannel("A").getbbox()
    crop = im.crop(box)
    scale = min((TEX_W - 8) / crop.width, (TEX_H - 8) / crop.height)
    w, h = int(crop.width * scale), int(crop.height * scale)
    art = crop.resize((w, h), Image.LANCZOS)
    tex = Image.new("RGBA", (TEX_W, TEX_H), (0, 0, 0, 0))
    tex.paste(art, (0, 0))
    tex.save(os.path.join(GEN, out_png), optimize=True)
    norm = [((x - box[0]) / crop.width, (y - box[1]) / crop.height) for x, y in anchors]
    return w, h, norm


def main():
    rows = []
    for name, pack, anchors, png in (("kPs5Art", "PS5", PS5, "controller_ps5.png"),
                                     ("kXboxArt", "Xbox Series", XBOX, "controller_xbox.png")):
        w, h, norm = build(pack, anchors, png)
        pts = ", ".join(f"{{{x:.4f}f, {y:.4f}f}}" for x, y in norm)
        rows.append(f"inline constexpr ControllerArt {name} = {{{w}, {h}, {{{pts}}}}};")
        print(f"{png}: {w}x{h} in {TEX_W}x{TEX_H}")
    with open(os.path.join(GEN, "controller_art.h"), "w", newline="\n") as f:
        f.write("// Generated by scripts/gen_controller_art.py - do not edit.\n")
        f.write("// Controller art: Zacksly, PS5 / Xbox Series Button Icons and Controls (CC BY 3.0, zacksly.itch.io),\n")
        f.write("// cropped and scaled.\n#pragma once\n\nnamespace gen {\n")
        f.write(f"inline constexpr int kControllerTexW = {TEX_W}, kControllerTexH = {TEX_H};\n")
        f.write("inline constexpr int kPs5ArtResource = 301, kXboxArtResource = 302;\n")
        f.write("struct ControllerArt {\n    int width, height;  // of the picture, top-left in the texture\n"
                "    float anchor[18][2];  // game buttons 0-15, left stick, right stick: fractions of the picture\n};\n")
        f.write("\n".join(rows) + "\n}  // namespace gen\n")


if __name__ == "__main__":
    main()
